baseURL = 'https://jzhoushang.github.io/'
languageCode = 'en-us'
title = 'Jason Shang'

theme = 'hello-friend-ng'
enableRobotsTXT = true

[caches]
    [caches.images]
    dir = ':cacheDir/images'

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    enableThemeToggle = true

    customCSS = ["/css/style.css"] 

    [params.logo]
    logoText = "jzhoushang"

    [[params.social]]
    name = "email"
    url  = "mailto:jzhoushang@gmail.com"

    [[params.social]]
    name = "github"
    url  = "https://github.com/jzhoushang"

    [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jzhoushang"

[menu]
    [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
 
